[package]
name = "vault_cli"
version = "0.1.0"
edition = "2024"

[dependencies]
redis = "0.32.3"
serde = { version = "1.0.194", features = ["derive"] }
serde_json = "1.0.140"
uuid = { version = "1.17.0", features = ["v4"] }
